SELECT 
    C.ID,
    IFNULL(D.CHILD_COUNT, 0) CHILD_COUNT
FROM 
    ECOLI_DATA C LEFT JOIN (
    SELECT
        A.ID,
        COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA A INNER JOIN ECOLI_DATA B
    ON A.ID = B.PARENT_ID 
    GROUP BY A.ID) D
ON C.ID = D.ID
ORDER BY C.ID;