WITH RECURSIVE tree AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, t.GENERATION + 1
    FROM ECOLI_DATA ED JOIN tree t ON t.ID = ED.PARENT_ID
)

SELECT COUNT(*) COUNT, t.GENERATION
FROM tree t LEFT JOIN ECOLI_DATA ed ON t.ID = ed.PARENT_ID
WHERE ed.ID IS NULL
GROUP BY t.GENERATION
ORDER BY t.GENERATION;