-- 코드를 입력하세요
SELECT ugb.TITLE, ugb.BOARD_ID, ugr.REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, DATE_FORMAT(ugr.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD ugb, USED_GOODS_REPLY ugr
WHERE 1=1 
AND ugb.BOARD_ID = ugr.BOARD_ID
AND ugb.CREATED_DATE >= '2022-10-01'
AND ugb.CREATED_DATE < '2022-11-01'
ORDER BY ugr.CREATED_DATE, ugb.TITLE;